env:
  commonjs: true
  es2020: true
  node: true
extends:
  - eslint:recommended
  - google
  - prettier
parserOptions:
  ecmaVersion: 11
plugins:
  - prettier
rules:
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
