service: telegram-reminder-aws-bot

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    OPEN_WEATHER_MAP_API_KEY: ${env:OPEN_WEATHER_MAP_API_KEY}
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    REMIND_CHAT_ID: ${env:REMIND_CHAT_ID}
    LOCALE: ${env:LOCALE}

functions:
  webhook:
    handler: main.webhook
    events:
      - http:
          path: webhook
          method: post
          cors: true
  remind:
    handler: main.remind
    events:
      - schedule: cron(30 13 ? * MON-FRI *)
