service: telegram-reminder-aws-bot

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

functions:
  webhook:
    handler: handler.webhook

    events:
      - http:
          path: webhook
          method: post
          cors: true
